### ISSUE TITLE
Add `exports` map to package.json for Node.js ESM resolution

### ISSUE THREAD

**Issue by TacB0sS** [lavrton/react-konva#857]
## Problem

`react-konva` provides an ESM build at `es/ReactKonva.js` via the `module` field, but has no `exports` map in `package.json`.

Node.js does not honor the `module` field (only bundlers like webpack/Vite do). So when code running in Node.js does `import 'react-konva'`, Node falls back to the `main` field → `lib/ReactKonva.js` (CJS).

That CJS entry internally does `require('konva')`. Since `konva@10+` is `"type": "module"`, Node refuses the `require()` with `ERR_REQUIRE_ESM`.

This breaks any Node-based test runner (mocha, jest, vitest in node mode) that transitively imports `react-konva`.

## Suggested fix

Add an `exports` map to `package.json`:

```json
"exports": {
  ".": {
    "import": "./es/ReactKonva.js",
    "require": "./lib/ReactKonva.js",
    "types": "./react-konva.d.ts"
  }
}
```

This lets Node resolve the ESM entry in ESM contexts while keeping CJS compatibility for older consumers.

## Reproduction

```bash
# In a "type": "module" package that depends on react-konva + konva@10
node --input-type=module -e "import 'react-konva'"
# → ERR_REQUIRE_ESM
```

## Versions

- `react-konva@18.2.14`
- `konva@10.3.0`
- Node.js v22.10.0

**Comment by lavrton** [comment]
Should be fixed in `react-konva@18.2.15`. Please confirm.

**Comment by BTMPL** [comment]
@lavrton I'm seeing the following since updating to 18.2.15:

```
packages/latex-editor/src/components/DrawingCanvas.tsx:2:42 - error TS7016: Could not find a declaration file for module 'react-konva'. '/path-redacted/node_modules/react-konva/es/ReactKonva.js' implicitly has an 'any' type.
  There are types at '/path-redacted/node_modules/react-konva/react-konva.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-konva' library may need to update its package.json or typings.

2 import { Layer, Line, Rect, Stage } from 'react-konva';
                                           ~~~~~~~~~~~~~
```

Working with node 25.5.0, npm 11.8.0

**Comment by lavrton** [comment]
@BTMPL can you please try `18.2.16`?

**Comment by BTMPL** [comment]
> [@BTMPL](https://github.com/BTMPL) can you please try `18.2.16`?

Sorry for late reply, looks like 18.2.16 solved the issue, thank you :)

**Comment by katotetsuro** [comment]
Hi @lavrton, thanks for the fix!

Could the `exports` map also be added to the 19.x line? 19.2.6 still has no `exports`, so on React 19 Node resolves `react-konva` to `lib/ReactKonva.js`, which `require("konva")`s the ESM-only konva 10.

**Comment by lavrton** [comment]
@katotetsuro published new version `19.2.7` with fixes.

**Comment by katotetsuro** [comment]
Verified that react-konva@19.2.7 build fine with Next.js@16 now. Thank you!
